import { zodResolver } from "@hookform/resolvers/zod";
import Head from "next/head";
import Image from "next/image";

import React, { useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "react-hot-toast";
import * as z from "zod";
import StorefrontLayout from "~/components/layouts/storefront-layout";
import { Button } from "~/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "~/components/ui/form";
import { Input } from "~/components/ui/input";
import { Textarea } from "~/components/ui/textarea";
import { api } from "~/utils/api";

const emailSchema = z.object({
  email: z.string().email(),
  name: z.string(),
  body: z.string(),
});

type EmailFormValues = z.infer<typeof emailSchema>;

export const ContactUsPage = () => {
  const [loading, setLoading] = useState(false);

  const form = useForm<EmailFormValues>({
    resolver: zodResolver(emailSchema),
    defaultValues: {
      email: undefined,
      name: undefined,
      body: undefined,
    },
  });

  const { mutate: sendEmail } = api.email.sendEmailInquiry.useMutation({
    onSuccess: () => {
      toast.success("Email sent. We will get back to you shortly.");
    },
    onError: (error) => {
      toast.error("Something went wrong");
      console.error(error);
    },
    onMutate: () => setLoading(true),
    onSettled: () => {
      setLoading(false);
    },
  });

  const onSubmit = (values: EmailFormValues) => {
    sendEmail(values);
  };
  return (
    <>
      <Head>
        <title>Contact Us | DreamWalker Studios</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StorefrontLayout bodyStyle="items-center justify-center flex">
        <div className="place-content: center flex  h-full flex-grow items-center justify-center ">
          <div className=" my-auto flex flex-col-reverse gap-y-8 space-y-10 px-4 py-10 max-md:items-center sm:px-6 md:flex-row lg:px-8 ">
            <div className="justify-left flex w-full flex-col gap-y-3 max-md:p-4 md:w-4/12">
              <>
                <h1 className="text-2xl">Have questions? Connect with us.</h1>
                <Form {...form}>
                  <form
                    onSubmit={(event) =>
                      void form.handleSubmit(onSubmit)(event)
                    }
                    className="space-y-5 py-5"
                  >
                    <FormField
                      control={form.control}
                      name="email"
                      render={({ field }) => (
                        <FormItem className="sm:col-span-3">
                          <FormLabel className="label">
                            <span className="label-text text-error">Email</span>
                          </FormLabel>
                          <FormControl>
                            <Input
                              disabled={loading}
                              placeholder="e.g. janedoe@example.com"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />{" "}
                    <FormField
                      control={form.control}
                      name="name"
                      render={({ field }) => (
                        <FormItem className="sm:col-span-3">
                          {" "}
                          <FormLabel className="label">
                            <span className="label-text text-error">Name</span>
                          </FormLabel>
                          <FormControl>
                            <Input
                              disabled={loading}
                              placeholder="e.g. Jane Doe"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                    <FormField
                      control={form.control}
                      name="body"
                      render={({ field }) => (
                        <FormItem className="sm:col-span-3">
                          {" "}
                          <FormLabel className="label">
                            <span className="label-text text-error">Body</span>
                          </FormLabel>
                          <FormControl>
                            <Textarea
                              disabled={loading}
                              placeholder="e.g. Hey! I had a question about a product."
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />{" "}
                    <Button className="ml-auto" type="submit">
                      Email Us
                    </Button>
                  </form>
                </Form>
              </>
            </div>

            <div className=" flex  w-full justify-end md:w-8/12  ">
              <Image
                src="/img/web_shopping.svg"
                alt="under development"
                width={500}
                height={500}
              />
            </div>
          </div>
        </div>
      </StorefrontLayout>{" "}
    </>
  );
};
