import type { GetServerSidePropsContext } from "next";
import { type FC } from "react";

import { api } from "~/utils/api";
import { authenticateSession } from "~/utils/auth";

import Head from "next/head";
import { AbsolutePageLoader } from "~/components/core/absolute-page-loader";
import AdminLayout from "~/components/layouts/AdminLayout";
import PageLoader from "~/components/ui/page-loader";
import { BlogPostForm } from "~/modules/blog-posts/admin/blog-post-form";

interface IProps {
  storeId: string;
  blogPostId: string;
}

const EditBlogPostPage: FC<IProps> = ({ storeId, blogPostId }) => {
  const { data: blogPost, isLoading } = api.blogPosts.getBlogPost.useQuery({
    blogPostId,
  });

  return (
    <>
      <Head>
        <title>Edit Blog Post | Admin Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>
        <div className="flex h-full flex-col bg-gray-50/25 dark:bg-slate-900">
          <div className="flex-1 space-y-4 p-8 pt-6">
            {isLoading && <AbsolutePageLoader />}
            {!isLoading && blogPost && <BlogPostForm initialData={blogPost} />}
          </div>
        </div>
      </AdminLayout>
    </>
  );
};

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const store = await authenticateSession(ctx);

  if (!store) {
    return {
      redirect: {
        destination: `/admin`,
        permanent: false,
      },
    };
  }

  return {
    props: {
      storeId: ctx.query.storeId,
      blogPostId: ctx.query.blogPostId,
    },
  };
}

export default EditBlogPostPage;
